sudo: required

services:
  - docker

before_install:
  - docker build -t yasardeen20/docker-react -f Dockerfile.dev .

script:
  - docker run yasardeen20/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app:  "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-766940135267"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"

